language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t 22222286s/docker-act -f Dockerfile .

script:
  - docker run  -e CI=true 22222286s/docker-act npm run test -- --coverage


